// <auto-generated />
using System;
using CapacityPlanning.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CapacityPlanning.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260531132217_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CapacityPlanning.Domain.Entities.Epic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstimatedDays")
                        .HasColumnType("int");

                    b.Property<Guid>("InitiativeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId");

                    b.HasIndex("TeamId");

                    b.ToTable("Epics");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d6cc8a42-3f3f-4a7f-9f56-759cd9bb2f0d"),
                            CreatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 932, DateTimeKind.Utc).AddTicks(9531),
                            DueDate = new DateTime(2025, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstimatedDays = 30,
                            InitiativeId = new Guid("22222222-0000-0000-0000-000000000001"),
                            Name = "Auth Service Rewrite",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TeamId = new Guid("11111111-0000-0000-0000-000000000003"),
                            UpdatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 932, DateTimeKind.Utc).AddTicks(9531)
                        },
                        new
                        {
                            Id = new Guid("5bb4d4e1-39f5-4e36-8863-ab73d196dc7d"),
                            CreatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 932, DateTimeKind.Utc).AddTicks(9546),
                            DueDate = new DateTime(2025, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstimatedDays = 40,
                            InitiativeId = new Guid("22222222-0000-0000-0000-000000000001"),
                            Name = "Portal UI Redesign",
                            StartDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TeamId = new Guid("11111111-0000-0000-0000-000000000002"),
                            UpdatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 932, DateTimeKind.Utc).AddTicks(9546)
                        },
                        new
                        {
                            Id = new Guid("3e586e3d-b8ac-4f85-a422-93d5037bc243"),
                            CreatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 932, DateTimeKind.Utc).AddTicks(9550),
                            DueDate = new DateTime(2025, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstimatedDays = 20,
                            InitiativeId = new Guid("22222222-0000-0000-0000-000000000002"),
                            Name = "API Gateway Setup",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TeamId = new Guid("11111111-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 932, DateTimeKind.Utc).AddTicks(9550)
                        },
                        new
                        {
                            Id = new Guid("eeabf2a7-a267-40de-b8c2-98f5ff310121"),
                            CreatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 932, DateTimeKind.Utc).AddTicks(9553),
                            DueDate = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstimatedDays = 25,
                            InitiativeId = new Guid("22222222-0000-0000-0000-000000000002"),
                            Name = "DB Query Optimization",
                            StartDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TeamId = new Guid("11111111-0000-0000-0000-000000000003"),
                            UpdatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 932, DateTimeKind.Utc).AddTicks(9553)
                        },
                        new
                        {
                            Id = new Guid("1bc1c608-4b3f-4923-a50e-839544fc3367"),
                            CreatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 932, DateTimeKind.Utc).AddTicks(9556),
                            DueDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstimatedDays = 60,
                            InitiativeId = new Guid("22222222-0000-0000-0000-000000000003"),
                            Name = "iOS App MVP",
                            StartDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TeamId = new Guid("11111111-0000-0000-0000-000000000004"),
                            UpdatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 932, DateTimeKind.Utc).AddTicks(9556)
                        },
                        new
                        {
                            Id = new Guid("335641b8-369f-4b2d-b2ce-e2885a564a4b"),
                            CreatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 932, DateTimeKind.Utc).AddTicks(9561),
                            DueDate = new DateTime(2025, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstimatedDays = 15,
                            InitiativeId = new Guid("22222222-0000-0000-0000-000000000003"),
                            Name = "Push Notifications",
                            StartDate = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TeamId = new Guid("11111111-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 932, DateTimeKind.Utc).AddTicks(9561)
                        });
                });

            modelBuilder.Entity("CapacityPlanning.Domain.Entities.Initiative", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Initiatives");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 933, DateTimeKind.Utc).AddTicks(1040),
                            Description = "Rebuild customer-facing portal",
                            Name = "New Customer Portal",
                            Priority = 2,
                            Status = 1,
                            TargetDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 933, DateTimeKind.Utc).AddTicks(1040)
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 933, DateTimeKind.Utc).AddTicks(1043),
                            Description = "Reduce p99 latency by 50%",
                            Name = "Performance Overhaul",
                            Priority = 3,
                            Status = 0,
                            TargetDate = new DateTime(2025, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 933, DateTimeKind.Utc).AddTicks(1043)
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 933, DateTimeKind.Utc).AddTicks(1046),
                            Description = "First native mobile app",
                            Name = "Mobile App Launch",
                            Priority = 1,
                            Status = 0,
                            TargetDate = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 933, DateTimeKind.Utc).AddTicks(1046)
                        });
                });

            modelBuilder.Entity("CapacityPlanning.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AvailabilityPercentage")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("24301970-e765-41cc-a410-0c856e2c02c8"),
                            AvailabilityPercentage = 100,
                            CreatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 933, DateTimeKind.Utc).AddTicks(1380),
                            Name = "Alice",
                            Role = "Tech Lead",
                            TeamId = new Guid("11111111-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 933, DateTimeKind.Utc).AddTicks(1380)
                        },
                        new
                        {
                            Id = new Guid("771e46ff-c7df-4a8a-9570-59849d6fe26f"),
                            AvailabilityPercentage = 100,
                            CreatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 933, DateTimeKind.Utc).AddTicks(1383),
                            Name = "Bob",
                            Role = "Senior Engineer",
                            TeamId = new Guid("11111111-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 933, DateTimeKind.Utc).AddTicks(1384)
                        },
                        new
                        {
                            Id = new Guid("6c4e4d13-16d6-422c-a46f-00dd876847cd"),
                            AvailabilityPercentage = 50,
                            CreatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 933, DateTimeKind.Utc).AddTicks(1390),
                            Name = "Carol",
                            Role = "Engineer",
                            TeamId = new Guid("11111111-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 933, DateTimeKind.Utc).AddTicks(1391)
                        },
                        new
                        {
                            Id = new Guid("4a4042da-4b6f-41f6-8431-1a5fca22d8a5"),
                            AvailabilityPercentage = 100,
                            CreatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 933, DateTimeKind.Utc).AddTicks(1393),
                            Name = "Dan",
                            Role = "Tech Lead",
                            TeamId = new Guid("11111111-0000-0000-0000-000000000002"),
                            UpdatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 933, DateTimeKind.Utc).AddTicks(1393)
                        },
                        new
                        {
                            Id = new Guid("e04017ff-c575-4d5f-ae59-ab4a5b557e49"),
                            AvailabilityPercentage = 100,
                            CreatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 933, DateTimeKind.Utc).AddTicks(1396),
                            Name = "Eva",
                            Role = "Engineer",
                            TeamId = new Guid("11111111-0000-0000-0000-000000000002"),
                            UpdatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 933, DateTimeKind.Utc).AddTicks(1396)
                        },
                        new
                        {
                            Id = new Guid("3e66925e-ee36-446c-a5b4-b69de52fae65"),
                            AvailabilityPercentage = 100,
                            CreatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 933, DateTimeKind.Utc).AddTicks(1398),
                            Name = "Frank",
                            Role = "Tech Lead",
                            TeamId = new Guid("11111111-0000-0000-0000-000000000003"),
                            UpdatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 933, DateTimeKind.Utc).AddTicks(1398)
                        },
                        new
                        {
                            Id = new Guid("a0ee4a96-f88d-46fb-974c-92ad09360a70"),
                            AvailabilityPercentage = 100,
                            CreatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 933, DateTimeKind.Utc).AddTicks(1402),
                            Name = "Grace",
                            Role = "Senior Engineer",
                            TeamId = new Guid("11111111-0000-0000-0000-000000000003"),
                            UpdatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 933, DateTimeKind.Utc).AddTicks(1403)
                        },
                        new
                        {
                            Id = new Guid("64bd88cf-329f-4914-9f66-d8675051249b"),
                            AvailabilityPercentage = 100,
                            CreatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 933, DateTimeKind.Utc).AddTicks(1405),
                            Name = "Henry",
                            Role = "Engineer",
                            TeamId = new Guid("11111111-0000-0000-0000-000000000003"),
                            UpdatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 933, DateTimeKind.Utc).AddTicks(1405)
                        },
                        new
                        {
                            Id = new Guid("cfa69d8c-cf8d-4a04-99de-1966b4853a65"),
                            AvailabilityPercentage = 100,
                            CreatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 933, DateTimeKind.Utc).AddTicks(1407),
                            Name = "Iris",
                            Role = "Tech Lead",
                            TeamId = new Guid("11111111-0000-0000-0000-000000000004"),
                            UpdatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 933, DateTimeKind.Utc).AddTicks(1407)
                        },
                        new
                        {
                            Id = new Guid("a0288db3-8923-457c-a2b6-85302f3dc156"),
                            AvailabilityPercentage = 50,
                            CreatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 933, DateTimeKind.Utc).AddTicks(1410),
                            Name = "Jack",
                            Role = "Engineer",
                            TeamId = new Guid("11111111-0000-0000-0000-000000000004"),
                            UpdatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 933, DateTimeKind.Utc).AddTicks(1410)
                        });
                });

            modelBuilder.Entity("CapacityPlanning.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OverheadPercentage")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 933, DateTimeKind.Utc).AddTicks(3327),
                            Name = "Platform",
                            OverheadPercentage = 25,
                            UpdatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 933, DateTimeKind.Utc).AddTicks(3327)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 933, DateTimeKind.Utc).AddTicks(3330),
                            Name = "Frontend",
                            OverheadPercentage = 20,
                            UpdatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 933, DateTimeKind.Utc).AddTicks(3330)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 933, DateTimeKind.Utc).AddTicks(3332),
                            Name = "Backend",
                            OverheadPercentage = 20,
                            UpdatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 933, DateTimeKind.Utc).AddTicks(3332)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 933, DateTimeKind.Utc).AddTicks(3334),
                            Name = "Mobile",
                            OverheadPercentage = 15,
                            UpdatedAt = new DateTime(2026, 5, 31, 13, 22, 16, 933, DateTimeKind.Utc).AddTicks(3335)
                        });
                });

            modelBuilder.Entity("CapacityPlanning.Domain.Entities.Epic", b =>
                {
                    b.HasOne("CapacityPlanning.Domain.Entities.Initiative", "Initiative")
                        .WithMany("Epics")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CapacityPlanning.Domain.Entities.Team", "Team")
                        .WithMany("Epics")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Initiative");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("CapacityPlanning.Domain.Entities.Person", b =>
                {
                    b.HasOne("CapacityPlanning.Domain.Entities.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("CapacityPlanning.Domain.Entities.Initiative", b =>
                {
                    b.Navigation("Epics");
                });

            modelBuilder.Entity("CapacityPlanning.Domain.Entities.Team", b =>
                {
                    b.Navigation("Epics");

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
