// <auto-generated />
using System;
using CapacityPlanning.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CapacityPlanning.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260531160010_RemoveStatus")]
    partial class RemoveStatus
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CapacityPlanning.Domain.Entities.Epic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstimatedDays")
                        .HasColumnType("int");

                    b.Property<Guid>("InitiativeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId");

                    b.HasIndex("TeamId");

                    b.ToTable("Epics");

                    b.HasData(
                        new
                        {
                            Id = new Guid("19b5901a-764f-42ed-8375-8f0e0f97ed2e"),
                            CreatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 360, DateTimeKind.Utc).AddTicks(9972),
                            DueDate = new DateTime(2025, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstimatedDays = 30,
                            InitiativeId = new Guid("22222222-0000-0000-0000-000000000001"),
                            Name = "Auth Service Rewrite",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = new Guid("11111111-0000-0000-0000-000000000003"),
                            UpdatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 360, DateTimeKind.Utc).AddTicks(9973)
                        },
                        new
                        {
                            Id = new Guid("09bb960a-9bea-4cee-96cb-96083ccd8ed5"),
                            CreatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 360, DateTimeKind.Utc).AddTicks(9978),
                            DueDate = new DateTime(2025, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstimatedDays = 40,
                            InitiativeId = new Guid("22222222-0000-0000-0000-000000000001"),
                            Name = "Portal UI Redesign",
                            StartDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = new Guid("11111111-0000-0000-0000-000000000002"),
                            UpdatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 360, DateTimeKind.Utc).AddTicks(9979)
                        },
                        new
                        {
                            Id = new Guid("9fc43a39-c3f0-443a-8597-ad9cfa8bbe67"),
                            CreatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 360, DateTimeKind.Utc).AddTicks(9984),
                            DueDate = new DateTime(2025, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstimatedDays = 20,
                            InitiativeId = new Guid("22222222-0000-0000-0000-000000000002"),
                            Name = "API Gateway Setup",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = new Guid("11111111-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 360, DateTimeKind.Utc).AddTicks(9984)
                        },
                        new
                        {
                            Id = new Guid("9566c70d-9cff-41ef-b1ab-795558f2101f"),
                            CreatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 361, DateTimeKind.Utc).AddTicks(6),
                            DueDate = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstimatedDays = 25,
                            InitiativeId = new Guid("22222222-0000-0000-0000-000000000002"),
                            Name = "DB Query Optimization",
                            StartDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = new Guid("11111111-0000-0000-0000-000000000003"),
                            UpdatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 361, DateTimeKind.Utc).AddTicks(6)
                        },
                        new
                        {
                            Id = new Guid("113db9ac-bd73-4700-87db-f4bd1d9f746f"),
                            CreatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 361, DateTimeKind.Utc).AddTicks(11),
                            DueDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstimatedDays = 60,
                            InitiativeId = new Guid("22222222-0000-0000-0000-000000000003"),
                            Name = "iOS App MVP",
                            StartDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = new Guid("11111111-0000-0000-0000-000000000004"),
                            UpdatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 361, DateTimeKind.Utc).AddTicks(12)
                        },
                        new
                        {
                            Id = new Guid("163c4b6b-7d32-4297-ba4e-895441907ca7"),
                            CreatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 361, DateTimeKind.Utc).AddTicks(15),
                            DueDate = new DateTime(2025, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstimatedDays = 15,
                            InitiativeId = new Guid("22222222-0000-0000-0000-000000000003"),
                            Name = "Push Notifications",
                            StartDate = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = new Guid("11111111-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 361, DateTimeKind.Utc).AddTicks(15)
                        });
                });

            modelBuilder.Entity("CapacityPlanning.Domain.Entities.Initiative", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Initiatives");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 361, DateTimeKind.Utc).AddTicks(5287),
                            Description = "Rebuild customer-facing portal",
                            Name = "New Customer Portal",
                            Priority = 2,
                            TargetDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 361, DateTimeKind.Utc).AddTicks(5287)
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 361, DateTimeKind.Utc).AddTicks(5294),
                            Description = "Reduce p99 latency by 50%",
                            Name = "Performance Rework",
                            Priority = 3,
                            TargetDate = new DateTime(2025, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 361, DateTimeKind.Utc).AddTicks(5294)
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 361, DateTimeKind.Utc).AddTicks(5298),
                            Description = "First native mobile app",
                            Name = "Mobile App Launch",
                            Priority = 1,
                            TargetDate = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 361, DateTimeKind.Utc).AddTicks(5298)
                        });
                });

            modelBuilder.Entity("CapacityPlanning.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AvailabilityPercentage")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2f437a50-01c9-4f17-bc5a-6bec957ef985"),
                            AvailabilityPercentage = 100,
                            CreatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 361, DateTimeKind.Utc).AddTicks(6012),
                            Name = "Alice",
                            Role = "Tech Lead",
                            TeamId = new Guid("11111111-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 361, DateTimeKind.Utc).AddTicks(6013)
                        },
                        new
                        {
                            Id = new Guid("7a810005-0e06-474b-bdf7-2f632f8b9272"),
                            AvailabilityPercentage = 100,
                            CreatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 361, DateTimeKind.Utc).AddTicks(6019),
                            Name = "Bob",
                            Role = "Senior Engineer",
                            TeamId = new Guid("11111111-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 361, DateTimeKind.Utc).AddTicks(6020)
                        },
                        new
                        {
                            Id = new Guid("0cf0336f-551a-4488-b656-f04c15b57c07"),
                            AvailabilityPercentage = 50,
                            CreatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 361, DateTimeKind.Utc).AddTicks(6030),
                            Name = "Carol",
                            Role = "Engineer",
                            TeamId = new Guid("11111111-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 361, DateTimeKind.Utc).AddTicks(6031)
                        },
                        new
                        {
                            Id = new Guid("f6d85bb0-1a64-40ba-b433-882d54af9ca7"),
                            AvailabilityPercentage = 100,
                            CreatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 361, DateTimeKind.Utc).AddTicks(6036),
                            Name = "Dan",
                            Role = "Tech Lead",
                            TeamId = new Guid("11111111-0000-0000-0000-000000000002"),
                            UpdatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 361, DateTimeKind.Utc).AddTicks(6037)
                        },
                        new
                        {
                            Id = new Guid("addd033d-00d6-4614-98e5-ecea9e00e145"),
                            AvailabilityPercentage = 100,
                            CreatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 361, DateTimeKind.Utc).AddTicks(6042),
                            Name = "Eva",
                            Role = "Engineer",
                            TeamId = new Guid("11111111-0000-0000-0000-000000000002"),
                            UpdatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 361, DateTimeKind.Utc).AddTicks(6043)
                        },
                        new
                        {
                            Id = new Guid("b1295501-5de7-4f0d-b1af-0359c0dc9b57"),
                            AvailabilityPercentage = 100,
                            CreatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 361, DateTimeKind.Utc).AddTicks(6049),
                            Name = "Frank",
                            Role = "Tech Lead",
                            TeamId = new Guid("11111111-0000-0000-0000-000000000003"),
                            UpdatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 361, DateTimeKind.Utc).AddTicks(6049)
                        },
                        new
                        {
                            Id = new Guid("7bc5a130-e358-4542-b7cc-d96e430747f9"),
                            AvailabilityPercentage = 100,
                            CreatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 361, DateTimeKind.Utc).AddTicks(6057),
                            Name = "Grace",
                            Role = "Senior Engineer",
                            TeamId = new Guid("11111111-0000-0000-0000-000000000003"),
                            UpdatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 361, DateTimeKind.Utc).AddTicks(6058)
                        },
                        new
                        {
                            Id = new Guid("690e20b1-09c5-440d-ab38-8729533c85a3"),
                            AvailabilityPercentage = 100,
                            CreatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 361, DateTimeKind.Utc).AddTicks(6063),
                            Name = "Henry",
                            Role = "Engineer",
                            TeamId = new Guid("11111111-0000-0000-0000-000000000003"),
                            UpdatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 361, DateTimeKind.Utc).AddTicks(6063)
                        },
                        new
                        {
                            Id = new Guid("5e55e482-43e6-42f0-8186-364f9ff04005"),
                            AvailabilityPercentage = 100,
                            CreatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 361, DateTimeKind.Utc).AddTicks(6068),
                            Name = "Iris",
                            Role = "Tech Lead",
                            TeamId = new Guid("11111111-0000-0000-0000-000000000004"),
                            UpdatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 361, DateTimeKind.Utc).AddTicks(6069)
                        },
                        new
                        {
                            Id = new Guid("46f8c18f-5be1-4184-976e-6334b2d6233b"),
                            AvailabilityPercentage = 50,
                            CreatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 361, DateTimeKind.Utc).AddTicks(6074),
                            Name = "Jack",
                            Role = "Engineer",
                            TeamId = new Guid("11111111-0000-0000-0000-000000000004"),
                            UpdatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 361, DateTimeKind.Utc).AddTicks(6074)
                        });
                });

            modelBuilder.Entity("CapacityPlanning.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OverheadPercentage")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 361, DateTimeKind.Utc).AddTicks(9938),
                            Name = "Platform",
                            OverheadPercentage = 25,
                            UpdatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 361, DateTimeKind.Utc).AddTicks(9939)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 361, DateTimeKind.Utc).AddTicks(9950),
                            Name = "Frontend",
                            OverheadPercentage = 20,
                            UpdatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 361, DateTimeKind.Utc).AddTicks(9951)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 361, DateTimeKind.Utc).AddTicks(9955),
                            Name = "Backend",
                            OverheadPercentage = 20,
                            UpdatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 361, DateTimeKind.Utc).AddTicks(9956)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 361, DateTimeKind.Utc).AddTicks(9960),
                            Name = "Mobile",
                            OverheadPercentage = 15,
                            UpdatedAt = new DateTime(2026, 5, 31, 16, 0, 10, 361, DateTimeKind.Utc).AddTicks(9960)
                        });
                });

            modelBuilder.Entity("CapacityPlanning.Domain.Entities.Epic", b =>
                {
                    b.HasOne("CapacityPlanning.Domain.Entities.Initiative", "Initiative")
                        .WithMany("Epics")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CapacityPlanning.Domain.Entities.Team", "Team")
                        .WithMany("Epics")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Initiative");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("CapacityPlanning.Domain.Entities.Person", b =>
                {
                    b.HasOne("CapacityPlanning.Domain.Entities.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("CapacityPlanning.Domain.Entities.Initiative", b =>
                {
                    b.Navigation("Epics");
                });

            modelBuilder.Entity("CapacityPlanning.Domain.Entities.Team", b =>
                {
                    b.Navigation("Epics");

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
